# -*- coding: utf-8 -*-
"""DBSCAN_Stroke (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILPUWfnUr1J4LWeTTLJRghcm3IafYpIc

# DBSCAN Clustering of Stroke Patient Profiles

**Goal:** Discover groups of patients with similar lifestyle and clinical characteristics using DBSCAN, an unsupervised, density-based clustering algorithm, then analyze how stroke cases are distributed among the discovered groups.

**Dataset:** Brain Stroke Dataset (Jillani SofTech, 2022), sourced from Kaggle: https://www.kaggle.com/datasets/jillanisofttech/brain-stroke-dataset
"""

import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, RobustScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import silhouette_score, davies_bouldin_score

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")

RANDOM_STATE = 42
DATA_PATH = "brain_stroke.csv"

plt.rcParams["figure.dpi"] = 300

"""## 1. Load the Dataset

The dataset is loaded directly from a local CSV file. If you are running this notebook in Google Colab, upload `brain_stroke.csv` first (either via the Colab file browser on the left, or by running the optional upload cell below), so that the path below resolves correctly.
"""

df = pd.read_csv(DATA_PATH)
print(f"Dataset shape: {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

"""## 2. Exploratory Data Analysis (EDA)

Before any preprocessing is applied, we first examine the raw data: its structure, missing values, and the distribution of key variables. This step, performed ahead of preprocessing, is what determines the preprocessing choices made in Section 3 (e.g., which columns need scaling vs. encoding), and it is also where the stroke-class imbalance central to this study's motivation becomes visible.
"""

# 2.1 Structure and missing values
print(df.info())
print("\nMissing values per column:\n", df.isnull().sum())

# 2.2 Stroke class balance — motivates the use of unsupervised clustering
# rather than a classifier that could be biased toward the majority class
stroke_counts = df["stroke"].value_counts(normalize=True).round(4)
print("Stroke class balance:\n", stroke_counts)

plt.figure(figsize=(4.5, 4))
sns.barplot(x=stroke_counts.index.map({0: "No Stroke", 1: "Stroke"}),
            y=stroke_counts.values, hue=stroke_counts.index, palette="tab10", legend=False)
plt.ylabel("Proportion of patients")
plt.title("Stroke Class Imbalance")
for i, v in enumerate(stroke_counts.values):
    plt.text(i, v + 0.01, f"{v:.1%}", ha="center")
plt.tight_layout()
plt.show()

# 2.3 Distribution of key numeric clinical features
numeric_cols_eda = ["age", "avg_glucose_level", "bmi"]
fig, axes = plt.subplots(1, 3, figsize=(13, 3.5))
for ax, col in zip(axes, numeric_cols_eda):
    sns.histplot(df[col], kde=True, ax=ax, color="#2E5C8A")
    ax.set_title(f"Distribution of {col}")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="white", palette="muted")

categorical_cols_eda = [
    "gender",
    "ever_married",
    "work_type",
    "Residence_type",
    "smoking_status"
]

fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()
total_samples = len(df)

for ax, col in zip(axes, categorical_cols_eda):
    # Order bars by frequency for clean visual hierarchy
    order = df[col].value_counts().index

    sns.countplot(
        y=col,
        data=df,
        ax=ax,
        order=order,
        color="#2B5C8F",
        alpha=0.85
    )

    clean_title = col.replace('_', ' ').title()
    ax.set_title(f"Distribution: {clean_title}", fontsize=11, fontweight="bold", pad=10)
    ax.set_xlabel("Count", fontsize=9)
    ax.set_ylabel("")

    # Remove clutter spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Annotate bars with exact count & percentage
    for p in ax.patches:
        count = int(p.get_width())
        percentage = (count / total_samples) * 100
        # Place label just outside the end of each bar
        ax.annotate(
            f"{count:,} ({percentage:.1f}%)",
            (p.get_width(), p.get_y() + p.get_height() / 2.),
            ha='left',
            va='center',
            xytext=(6, 0),
            textcoords='offset points',
            fontsize=8.5,
            fontweight="medium",
            color="#333333"
        )

    # Adjust x-limit to leave room for bar labels
    ax.set_xlim(0, ax.get_xlim()[1] * 1.25)

# Hide unused subplot
for ax in axes[len(categorical_cols_eda):]:
    ax.axis("off")

plt.suptitle("Categorical Feature Distributions", fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(3, 1, figsize=(10, 6), sharex=False)

for ax, col in zip(axes, numeric_cols_eda):
    sns.boxplot(
        x=df[col],
        ax=ax,
        width=0.35,
        color="#8da0cb",
        fliersize=5,
        flierprops={"markerfacecolor": "#e78ac3", "markeredgecolor": "none", "alpha": 0.6}
    )

    clean_title = col.replace('_', ' ').title()
    ax.set_title(clean_title, fontsize=11, fontweight="bold", loc="left")
    ax.set_xlabel("")
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.set_yticks([])

plt.suptitle("Outlier Profiles across Clinical Features", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

"""### 2.4.1 Quantifying Outliers (IQR Method)

Figure 7 shows outliers visually, but for the report we also quantify them numerically using the standard IQR rule: a value is flagged as an outlier if it falls below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. These are **not treated as data errors** — in this dataset, high `avg_glucose_level` and `bmi` values correspond to genuinely diabetic/obese patients, who are clinically relevant to stroke risk rather than noise to be removed. They are therefore kept in the dataset; the decision on how to *handle* them (without deleting them) is addressed in Section 3.3.
"""

outlier_summary = []
for col in numeric_cols_eda:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    outlier_summary.append({
        "feature": col, "Q1": round(q1, 2), "Q3": round(q3, 2),
        "lower_bound": round(lower, 2), "upper_bound": round(upper, 2),
        "n_outliers": n_outliers, "pct_outliers": round(n_outliers / len(df) * 100, 2)
    })

outlier_df = pd.DataFrame(outlier_summary)
outlier_df

# 2.4 Correlation among numeric/binary features (helps flag redundancy before
# features are carried into clustering)
corr_cols = ["age", "hypertension", "heart_disease", "avg_glucose_level", "bmi", "stroke"]
plt.figure(figsize=(5.5, 4.5))
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="vlag", center=0)
plt.title("Correlation Matrix of Numeric/Binary Features")
plt.tight_layout()
plt.show()

"""## 3. Data Preprocessing

Guided by the EDA above, the following preprocessing steps are applied:

- **Numeric features with outliers** (`age`, `avg_glucose_level`, `bmi`) -> `RobustScaler`, which scales using the median and interquartile range (IQR) instead of the mean and standard deviation. This was chosen specifically because Section 2.4.1 identified outliers in `avg_glucose_level` and `bmi`; `RobustScaler` reduces their influence on distance calculations without deleting any patient records, preserving the high-glucose/high-BMI patients who are most relevant to stroke risk.
- **Binary clinical features** (`hypertension`, `heart_disease`) -> `StandardScaler`, since these are already 0/1 flags with no outlier concern.
- **Categorical features** -> `OneHotEncoder`, since DBSCAN operates on numeric distances and cannot use raw category labels directly.
- `stroke` is held out entirely and only reintroduced later (Section 8) to *interpret* the clusters — it is never used to form them.
"""

stroke_label = df["stroke"].copy()
X_raw = df.drop(columns=["stroke"])

numeric_cols = ["age", "avg_glucose_level", "bmi"]   # outlier-prone -> RobustScaler
binary_cols = ["hypertension", "heart_disease"]       # already 0/1 -> StandardScaler
categorical_cols = ["gender", "ever_married", "work_type", "Residence_type", "smoking_status"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", RobustScaler(), numeric_cols),
        ("bin", StandardScaler(), binary_cols),
        ("cat", OneHotEncoder(drop=None, handle_unknown="ignore"), categorical_cols),
    ]
)
X_processed = preprocessor.fit_transform(X_raw)
# OneHotEncoder can return a sparse matrix; densify for downstream PCA/DBSCAN use
if hasattr(X_processed, "toarray"):
    X_processed = X_processed.toarray()

# Reduce to 2 dimensions for stable DBSCAN and plotting
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_processed)

print("Data successfully preprocessed and reduced to 2 dimensions!")

print("Processed feature matrix shape:", X_processed.shape)

def show_transformation(column_name):
    feature_names = preprocessor.get_feature_names_out()

    print("=" * 60)
    print(f"Original Column: {column_name}")

    if column_name in numeric_cols:
        print("Transformation Method: RobustScaler (median/IQR-based, robust to outliers)")
    elif column_name in binary_cols:
        print("Transformation Method: StandardScaler")
    elif column_name in categorical_cols:
        print("Transformation Method: One-Hot Encoding")

    print("-" * 60)
    print("New Feature(s) After Transformation:")

    matching_features = [
        feature.replace("num__", "").replace("bin__", "").replace("cat__", "")
        for feature in feature_names
        if column_name.lower() in feature.lower()
    ]

    for i, feature in enumerate(matching_features, 1):
        print(f"{i}. {feature}")

    print("=" * 60)


# Test
show_transformation("age")
show_transformation("gender")
show_transformation("work_type")

"""## 4. Dimensionality Reduction (PCA)

One-hot encoding expands the categorical columns into many sparse binary features, which can dilute distance calculations and slow DBSCAN down. Principal Component Analysis (PCA) is applied to compress the processed feature matrix down to the components that jointly explain at least 90% of the total variance, while a separate 2-component projection is kept purely for visualization in Section 6.
"""

pca_full = PCA(random_state=RANDOM_STATE).fit(X_processed)
cum_var = np.cumsum(pca_full.explained_variance_ratio_)
n_components = int(np.argmax(cum_var >= 0.90) + 1)
print(f"Components needed for 90% variance: {n_components}")

pca = PCA(n_components=n_components, random_state=RANDOM_STATE)
X_pca = pca.fit_transform(X_processed)

# Separate 2D projection kept only for the scatter plot in Section 6
pca_2d = PCA(n_components=2, random_state=RANDOM_STATE)
X_2d = pca_2d.fit_transform(X_processed)

plt.figure(figsize=(6, 4))
plt.plot(range(1, len(cum_var) + 1), cum_var, marker="o", ms=3)
plt.axhline(0.90, color="red", linestyle="--", label="90% variance")
plt.axvline(n_components, color="green", linestyle=":", label=f"{n_components} components")
plt.xlabel("Number of principal components")
plt.ylabel("Cumulative explained variance")
plt.title("PCA Explained Variance")
plt.legend()
plt.tight_layout()
plt.show()

feature_names = preprocessor.get_feature_names_out()

loading_df = pd.DataFrame(
    pca.components_.T,
    index=feature_names,
    columns=[f"PC{i+1}" for i in range(n_components)]
)

print(loading_df)

"""## 5. Choosing DBSCAN Parameters (`eps` and `min_samples`)

DBSCAN (Ester et al., 1996) requires two parameters:

- `min_samples`: the minimum number of neighboring points required for a point to be considered a "core point". We use the common heuristic of `2 x number of PCA dimensions`.
- `eps`: the neighborhood radius. This is estimated from the "elbow" of the sorted k-distance curve — the point where distances to the `min_samples`-th nearest neighbor start increasing sharply, indicating the transition from dense to sparse regions of the data.
"""

min_samples = 2 * X_pca.shape[1]
neighbors = NearestNeighbors(n_neighbors=min_samples).fit(X_pca)
distances, _ = neighbors.kneighbors(X_pca)
k_distances = np.sort(distances[:, -1])

# Elbow = point of maximum curvature in the second half of the sorted curve,
# where distances start increasing sharply (dense -> sparse transition)
diffs = np.diff(k_distances)
elbow_idx = np.argmax(diffs[len(diffs) // 2:]) + len(diffs) // 2
eps_candidate = k_distances[elbow_idx]

plt.figure(figsize=(6, 4))
plt.plot(k_distances)
plt.scatter([elbow_idx], [eps_candidate], color="red", zorder=5,
            label=f"Elbow (eps ~= {eps_candidate:.3f})")
plt.xlabel("Points sorted by distance")
plt.ylabel(f"Distance to {min_samples}-th nearest neighbor")
plt.title("K-Distance Graph for eps Selection")
plt.legend()
plt.tight_layout()
plt.show()

print(f"min_samples = {min_samples}, elbow-suggested eps ~= {eps_candidate:.3f}")

"""Patients before the elbow have relatively small distances to their `min_samples`-th nearest neighbor, meaning they sit in dense regions of the feature space. Patients after the elbow require much larger distances to find enough neighbors, meaning they sit in sparser, more atypical regions and are more likely to be flagged as noise by DBSCAN.

## 6. Grid Search Around the Elbow Estimate

The elbow method gives a good starting estimate, but a small grid search around it is used to fine-tune `eps`. Each candidate is scored using both the Silhouette Score (Rousseeuw, 1987) and the Davies-Bouldin Index (Davies & Bouldin, 1979), restricted to candidates that produce between 2 and 8 clusters with under 40% of points labeled as noise, so that the final result is both statistically well-separated and practically interpretable.
"""

results = []
eps_range = np.round(np.arange(max(0.3, eps_candidate - 0.6), eps_candidate + 0.9, 0.15), 2)

for eps in eps_range:
    labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(X_pca)
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise_ratio = np.mean(labels == -1)

    sil, dbi = np.nan, np.nan
    if n_clusters >= 2:
        mask = labels != -1
        if mask.sum() > 1 and len(set(labels[mask])) >= 2:
            sil = silhouette_score(X_pca[mask], labels[mask])
            dbi = davies_bouldin_score(X_pca[mask], labels[mask])

    results.append((eps, n_clusters, noise_ratio, sil, dbi))

results_df = pd.DataFrame(
    results, columns=["eps", "n_clusters", "noise_ratio", "silhouette", "davies_bouldin"]
)
results_df

# Select the eps that maximizes Silhouette Score among valid candidates
# (2-8 clusters, <40% noise). Falls back to the first row if none qualify.
valid = results_df[(results_df["n_clusters"].between(2, 8)) & (results_df["noise_ratio"] < 0.4)]
best_row = valid.loc[valid["silhouette"].idxmax()] if len(valid) else results_df.iloc[0]
best_eps = best_row["eps"]
print(f"Selected eps = {best_eps}")

dbscan = DBSCAN(eps=best_eps, min_samples=min_samples)
cluster_labels = dbscan.fit_predict(X_pca)
df["cluster"] = cluster_labels

n_clusters_final = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
noise_ratio_final = np.mean(cluster_labels == -1)
mask = cluster_labels != -1

sil_final = silhouette_score(X_pca[mask], cluster_labels[mask]) if n_clusters_final >= 2 else np.nan
dbi_final = davies_bouldin_score(X_pca[mask], cluster_labels[mask]) if n_clusters_final >= 2 else np.nan

print(f"\nFinal DBSCAN: eps={best_eps}, min_samples={min_samples}")
print(f"Clusters found (excluding noise): {n_clusters_final}")
print(f"Noise points: {(~mask).sum()} ({noise_ratio_final:.2%})")
print(f"Silhouette Score: {sil_final:.3f}  (closer to +1 is better)")
print(f"Davies-Bouldin Index: {dbi_final:.3f}  (lower is better)")

"""## 7. Visualize the Clusters (PCA 2D Projection)"""

plt.figure(figsize=(7, 6))
palette = sns.color_palette("tab10", n_colors=max(n_clusters_final, 1))
for lbl in sorted(set(cluster_labels)):
    mask_l = cluster_labels == lbl
    color = "lightgray" if lbl == -1 else palette[lbl % len(palette)]
    label_name = "Noise" if lbl == -1 else f"Cluster {lbl}"
    plt.scatter(X_2d[mask_l, 0], X_2d[mask_l, 1], s=12, color=color, label=label_name, alpha=0.6)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("DBSCAN Clusters (PCA 2D Projection)")
plt.legend(markerscale=2, fontsize=8)
plt.tight_layout()
plt.show()

# 6. Visualization & Stroke Risk Analysis
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: The Clusters
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=cluster_labels, palette="tab10", legend="full", ax=ax1)
ax1.set_title("DBSCAN Clusters (PCA 2D Projection)")
ax1.set_xlabel("Principal Component 1")
ax1.set_ylabel("Principal Component 2")
ax1.legend(title="Cluster (-1 is Noise)")

# Plot 2: Stroke Distribution per Cluster
# Calculate percentage of stroke cases in each cluster
stroke_rates = df[df['cluster'] != -1].groupby('cluster')['stroke'].mean() * 100

sns.barplot(x=stroke_rates.index, y=stroke_rates.values, ax=ax2, palette="Reds")
ax2.set_title("Stroke Risk per Cluster (%)")
ax2.set_xlabel("Cluster")
ax2.set_ylabel("Percentage of Stroke Cases")

for i, v in enumerate(stroke_rates.values):
    ax2.text(i, v + 0.1, f"{v:.1f}%", ha="center")

plt.tight_layout()
plt.show()

"""## 8. Stroke Distribution Across Clusters

The held-out `stroke` label is reintroduced here purely for interpretation — it played no role in forming the clusters above.
"""

cross = pd.crosstab(df["cluster"], df["stroke"], margins=True)
cross.columns = ["No Stroke", "Stroke", "Total"] if cross.shape[1] == 3 else cross.columns
cross["Stroke Rate (%)"] = (cross["Stroke"] / cross["Total"] * 100).round(2)
cross

plot_df = df[df["cluster"] != -1] if -1 in df["cluster"].values else df
stroke_rate_by_cluster = plot_df.groupby("cluster")["stroke"].mean().mul(100).round(2)

plt.figure(figsize=(7, 4.5))
bars = plt.bar(stroke_rate_by_cluster.index.astype(str), stroke_rate_by_cluster.values,
                color=sns.color_palette("tab10", len(stroke_rate_by_cluster)))
overall_rate = df["stroke"].mean() * 100
plt.axhline(overall_rate, color="red", linestyle="--",
            label=f"Overall rate ({overall_rate:.2f}%)")
plt.xlabel("Cluster")
plt.ylabel("Stroke Rate (%)")
plt.title("Stroke Rate by Cluster")
plt.legend()
for bar, val in zip(bars, stroke_rate_by_cluster.values):
    plt.text(bar.get_x() + bar.get_width() / 2, val + 0.2, f"{val:.1f}%", ha="center", fontsize=8)
plt.tight_layout()
plt.show()

"""## 9. Cluster Profiles (Mean Characteristics per Cluster)

Summarizing each cluster's average clinical/lifestyle characteristics helps translate the abstract cluster labels into clinically meaningful patient profiles (e.g., a "low-risk" vs. "high-risk" group).
"""

profile_cols = ["age", "hypertension", "heart_disease", "avg_glucose_level", "bmi", "stroke"]
cluster_profile = df.groupby("cluster")[profile_cols].mean().round(2)
cluster_profile["size"] = df.groupby("cluster").size()
cluster_profile

for col in ["work_type", "smoking_status"]:
    mode_table = df.groupby("cluster")[col].agg(lambda x: x.value_counts().idxmax())
    print(f"Most common {col} per cluster:")
    print(mode_table, "\n")

"""## 9b. Identifying High-Risk Patient Groups

This step directly addresses the project goal: having discovered patient groups based purely on lifestyle and clinical characteristics (Sections 5-6), we now check whether any group shows a stroke rate meaningfully above the dataset's overall rate. A cluster is flagged as **elevated-risk** if its stroke rate exceeds the overall rate by a chosen margin (default: 1.5x).
"""

RISK_MULTIPLIER = 1.5  # a cluster is "elevated-risk" if its stroke rate > 1.5x the overall rate

overall_rate = df["stroke"].mean() * 100
cluster_rates = df[df["cluster"] != -1].groupby("cluster")["stroke"].mean().mul(100)

print(f"Overall stroke rate: {overall_rate:.2f}%\n")
for cluster_id, rate in cluster_rates.items():
    flag = "  <-- ELEVATED-RISK GROUP" if rate > overall_rate * RISK_MULTIPLIER else ""
    print(f"Cluster {cluster_id}: stroke rate = {rate:.2f}%{flag}")

elevated_clusters = cluster_rates[cluster_rates > overall_rate * RISK_MULTIPLIER].index.tolist()
if elevated_clusters:
    print(f"\nElevated-risk cluster(s) identified: {elevated_clusters}")
    print("Their average characteristics (compare against the cluster_profile table above):")
    display(df[df["cluster"].isin(elevated_clusters)][profile_cols].mean().round(2))
else:
    print("\nNo cluster exceeded the elevated-risk threshold; consider lowering RISK_MULTIPLIER "
          "or reviewing whether the chosen eps/min_samples produced meaningful separation.")

"""## 10. Summary

- Report the final `eps`, `min_samples`, number of clusters, noise ratio, Silhouette Score, and Davies-Bouldin Index here once the notebook has been run on the full dataset.
- Compare the stroke rate of each cluster (Section 8) against the overall stroke rate to identify which cluster(s) represent a higher-risk patient profile.
- Cross-reference these findings with the K-Means and MeanShift notebooks to determine which algorithm best separates stroke risk on this dataset (see Section 2.0 Methodology of the report).

## References

- Davies, D. L., & Bouldin, D. W. (1979). A cluster separation measure. *IEEE Transactions on Pattern Analysis and Machine Intelligence*, PAMI-1(2), 224-227. https://doi.org/10.1109/TPAMI.1979.4766909
- Ester, M., Kriegel, H.-P., Sander, J., & Xu, X. (1996). A density-based algorithm for discovering clusters in large spatial databases with noise. In *Proceedings of the Second International Conference on Knowledge Discovery and Data Mining (KDD-96)* (pp. 226-231). AAAI Press. https://dl.acm.org/doi/10.5555/3001460.3001507
- Jillani SofTech. (2022). *Brain Stroke Dataset* [Data set]. Kaggle. https://www.kaggle.com/datasets/jillanisofttech/brain-stroke-dataset
- Rousseeuw, P. J. (1987). Silhouettes: A graphical aid to the interpretation and validation of cluster analysis. *Journal of Computational and Applied Mathematics*, 20, 53-65. https://doi.org/10.1016/0377-0427(87)90125-7

## 11. (Optional) Save Results to Files

Only needed if you want to download the figures/tables for your report — everything is already displayed inline above.
"""

# Uncomment to save outputs, then download via the Colab file browser (left sidebar)
# cross.to_csv("cluster_stroke_distribution.csv")
# cluster_profile.to_csv("cluster_profiles.csv")